---
- name: add/remove packages
  apt:
    name: "{{ packages }}"
    state: "{{ packages_state | default(\"present\") }}"
    update_cache: "{{ packages_update_cache | default(omit) }}"
    cache_valid_time: "{{ packages_cache_valid_time }}"
